# Analytics
analytics:
  provider               : "google-gtag"
  # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-CXZM6X9V00"
    anonymize_ip         : # true, false (default)
